services:
    db:
        image: postgres:13
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - aml_postgres_data:/var/lib/postgresql/data
        networks:
            - aml_network # This network needs to be created by this compose file

volumes:
    aml_postgres_data:

networks:
    aml_network:
        driver: bridge # This creates the shared network