# docker-compose.yml
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
        container_name: postgres_db
        ports:
            - "6543:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend
        restart: always
   
    ingestion:
        build:
            context: ./ingestion
        container_name: ingestion
        env_file:
            - ./ingestion/.env
        volumes:
            - ./data:/app/data
        depends_on:
            - db
        networks:
            - backend
   
    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        ports:
            - "2181:2181"
        networks:
            - backend
           
    kafka:
        image: confluentinc/cp-kafka:7.6.0
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
        networks:
            - backend

    init-kafka:
        image: confluentinc/cp-kafka:7.6.0
        container_name: init_kafka
        depends_on:
            - kafka
        command: |
            bash -c "
            echo 'Waiting for Kafka to be ready...'
            cub kafka-ready -b kafka:9092 1 20
            echo 'Creating Kafka topics...'
            kafka-topics --create --if-not-exists --topic transactions --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
            kafka-topics --create --if-not-exists --topic ownership_graph --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
            kafka-topics --create --if-not-exists --topic enriched_transactions --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
            echo 'Kafka topics created successfully!'
            "
        networks:
            - backend
        # Ensure this service finishes before streaming starts if streaming relies on topics existing
        # No restart policy for init services

    streaming:
        build: ./streaming
        container_name: streaming
        volumes:
            - ./data:/app/data
        env_file:
            - ./streaming/.env
        depends_on:
            - kafka
            - init-kafka
            - db
        networks:
            - backend


volumes:
    pg_data:


networks:
    backend:
        driver: bridge