services:
    db:
        image: postgres:13
        container_name: postgres_db
        ports:
            - "5431:5432"
        environment:
            POSTGRES_DB: development
            POSTGRES_USER: postgres_container_user
            POSTGRES_PASSWORD: pgdockerpass
            # POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            # - ./postgres-config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
            - aml_postgres_data:/var/lib/postgresql/data
        networks:
            - aml_network
        restart: always

volumes:
    aml_postgres_data:

networks:
    aml_network:
        driver: bridge