services:
    postgres:
        image: postgres:13
        container_name: postgres-db
        environment:
            POSTGRES_USER: ${DC_POSTGRES_USER}
            POSTGRES_PASSWORD: ${DC_POSTGRES_PASS}
            POSTGRES_DB: ${DC_POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - aml_network

    dbt:
        image: fishtownanalytics/dbt:1.0.0
        container_name: dbt-container
        environment:
            DBT_PROFILES_DIR: /root/.dbt
        volumes:
            - ./risk_engine_dbt:/usr/app/risk_engine_dbt
        working_dir: /usr/app/risk_engine_dbt
        networks:
            - aml_network
        depends_on:
            - postgres

volumes:
    postgres-data:

networks:
    aml_network:
        driver: bridge
