services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            # POSTGRES_HOST_AUTH_METHOD: trust
        container_name: postgres_db
        ports:
            - "6543:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend
        restart: always
    
    ingestion:
        build:
            context: ./ingestion
        container_name: ingestion
        env_file:
            - ./ingestion/.env
        volumes:
            - ./data:/app/data
        depends_on:
            - db
        networks:
            - backend

volumes:
    pg_data:

networks:
    backend:
        driver: bridge