services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASS}
            # POSTGRES_HOST_AUTH_METHOD: trust
        container_name: postgres_db
        ports:
            - "6543:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - backend
        restart: always
    
    ingestion:
        build:
            context: ./ingestion
        container_name: ingestion
        env_file:
            - ./ingestion/.env
        volumes:
            - ./data:/app/data
        depends_on:
            - db
        networks:
            - backend
    
    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        ports:
            - "2181:2181"
        networks:
            - backend
            
    kafka:
        image: confluentinc/cp-kafka:7.6.0
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - backend

    streaming:
        build: ./streaming
        volumes:
            - ./data:/app/data
        env_file:
            - ./streaming/.env
        depends_on:
            - kafka
        networks:
            - backend

volumes:
    pg_data:

networks:
    backend:
        driver: bridge