services:
    db:
        image: postgres:13
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${DC_POSTGRES_USER}
            POSTGRES_PASSWORD: ${DC_POSTGRES_PASS} # Change this password for security
            POSTGRES_DB: ${DC_POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - aml_postgres_data:/var/lib/postgresql/data
        networks:
            - aml_network

volumes:
    aml_postgres_data:

networks:
    aml_network:
        driver: bridge