CREATE TABLE IF NOT EXISTS enriched_transactions (
    transaction_id VARCHAR(255) PRIMARY KEY,
    time NUMERIC,
    v1 NUMERIC,
    v2 NUMERIC,
    v3 NUMERIC,
    v4 NUMERIC,
    v5 NUMERIC,
    v6 NUMERIC,
    v7 NUMERIC,
    v8 NUMERIC,
    v9 NUMERIC,
    v10 NUMERIC,
    v11 NUMERIC,
    v12 NUMERIC,
    v13 NUMERIC,
    v14 NUMERIC,
    v15 NUMERIC,
    v16 NUMERIC,
    v17 NUMERIC,
    v18 NUMERIC,
    v19 NUMERIC,
    v20 NUMERIC,
    v21 NUMERIC,
    v22 NUMERIC,
    v23 NUMERIC,
    v24 NUMERIC,
    v25 NUMERIC,
    v26 NUMERIC,
    v27 NUMERIC,
    v28 NUMERIC,
    amount NUMERIC,
    class INTEGER,

    customer_id VARCHAR(255),
    company_number VARCHAR(255),

    kyc_full_name VARCHAR(255),
    kyc_email VARCHAR(255),
    kyc_phone_number VARCHAR(255),
    kyc_address TEXT,
    kyc_country VARCHAR(100),
    kyc_date_of_birth DATE,
    kyc_gender VARCHAR(50),
    kyc_occupation VARCHAR(255),
    kyc_registration_date TIMESTAMP,
    kyc_last_login_ip VARCHAR(50),
    kyc_device_id VARCHAR(255),
    kyc_kyc_status VARCHAR(50),
    kyc_risk_score NUMERIC(5,2),
    kyc_updated_at TIMESTAMP,

    -- Ownership links (as JSONB)
    ownership_links_json JSONB
);